let mostrar= document.getElementById('mostrar')
let n1=document.getElementById('n1')
let operador=document.getElementById('operador')
let n2=document-getElementById('n2')
let uno=document.getElementById('uno')
let dos=document.getElementById('dos')
let tres=document.getElementById('tres')
let cuatro=document.getElementById('cuatro')
let cinco=document.getElementById('cinco')
let seis=document.getElementById('seis')
let siete=document.getElementById('siete')
let ocho=document.getElementById('ocho')
let nueve=document.getElementById('nueve')
let cero=document.getElementById('cero')
let mas=document.getElementById('mas')
let menos=document.getElementById('menos')
let por=document.getElementById('por')
let divir=document.getElementById('divir')
let off=document.getElementById('apagar')
let igual=document.getElementById('igual')

uno.addEventListener('click',=>{
    
})